wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
backbone:
  desc: null
  value: densenet121
bnm_loss_weight:
  desc: null
  value: 0.0
bnm_start_epoch:
  desc: null
  value: 0
checkpoint:
  desc: null
  value: null
class_names:
  desc: null
  value:
  - Normal
  - OA
  - ONFH
  - DDH
class_num:
  desc: null
  value: 4
class_num_dict:
  desc: null
  value:
  - 6046.0
  - 5793.0
  - 9832.0
  - 4404.0
crop_size:
  desc: null
  value: 224
drop:
  desc: null
  value: 0
epochs:
  desc: null
  value: 100
exp:
  desc: null
  value: test
gpu_ids:
  desc: null
  value: 0,1
labeled_bs:
  desc: null
  value: 32
labeled_num:
  desc: null
  value: 1000
lr:
  desc: null
  value: 0.0001
manualSeed:
  desc: null
  value: 1337
pretrained:
  desc: null
  value: true
resize:
  desc: null
  value: 256
root_path:
  desc: null
  value: ../../dataset/hip_4cls/training_data/
start_epoch:
  desc: null
  value: 0
task:
  desc: null
  value: hip_4cls
test_bs:
  desc: null
  value: 64
test_file:
  desc: null
  value: ../../dataset/hip_4cls/testing.txt
train_bs:
  desc: null
  value: 64
train_file:
  desc: null
  value: ../../dataset/hip_4cls/training.txt
val_file:
  desc: null
  value: ../../dataset/hip_4cls/validation.txt
vat_filter_batch:
  desc: null
  value: false
vat_filter_num:
  desc: null
  value: 16
vat_loss_weight:
  desc: null
  value: 0.0
vat_start_epoch:
  desc: null
  value: 0
