wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
backbone:
  desc: null
  value: densenet121
base_lr:
  desc: null
  value: 0.0001
baseline:
  desc: null
  value: 0
batch_size:
  desc: null
  value: 32
bnm_loss:
  desc: null
  value: 0
bnm_loss_improve:
  desc: null
  value: 0
bnm_loss_weight:
  desc: null
  value: 1.0
class_names:
  desc: null
  value:
  - Atelectasis
  - Cardiomegaly
  - Effusion
  - Infiltration
  - Mass
  - Nodule
  - Pneumonia
  - Pneumothorax
  - Consolidation
  - Edema
  - Emphysema
  - Fibrosis
  - Pleural_Thickening
  - Hernia
class_num:
  desc: null
  value:
  - 11559.0
  - 2776.0
  - 13317.0
  - 19894.0
  - 5782.0
  - 6331.0
  - 1431.0
  - 5302.0
  - 4667.0
  - 2303.0
  - 2516.0
  - 1686.0
  - 3385.0
  - 227.0
consistency:
  desc: null
  value: 1
consistency_began_epoch:
  desc: null
  value: 0
consistency_rampup:
  desc: null
  value: 30
consistency_relation_weight:
  desc: null
  value: 1.0
consistency_type:
  desc: null
  value: mse
csv_file_test:
  desc: null
  value: ../dataset/chest/testing.csv
csv_file_train:
  desc: null
  value: ../dataset/chest/training.csv
csv_file_val:
  desc: null
  value: ../dataset/chest/validation.csv
deterministic:
  desc: null
  value: 1
drop_rate:
  desc: null
  value: 0.2
ema_consistency:
  desc: null
  value: 1
ema_decay:
  desc: null
  value: 0.99
entropy_loss:
  desc: null
  value: 0
entropy_loss_weight:
  desc: null
  value: 1.0
epochs:
  desc: null
  value: 100
exp:
  desc: null
  value: 0709_wcp_test
global_step:
  desc: null
  value: 0
gpu:
  desc: null
  value: 0,1
labeled_bs:
  desc: null
  value: 8
labeled_rate:
  desc: null
  value: 0.2
resize:
  desc: null
  value: 320
resume:
  desc: null
  value: null
root_path:
  desc: null
  value: ../dataset/chest/training_data/
seed:
  desc: null
  value: 22000
start_epoch:
  desc: null
  value: 0
supCon_loss:
  desc: null
  value: 0
supCon_loss_weight:
  desc: null
  value: 1.0
task:
  desc: null
  value: chest
vat_dis_type:
  desc: null
  value: mae
vat_filter_batch:
  desc: null
  value: true
vat_filter_num:
  desc: null
  value: 24
vat_loss:
  desc: null
  value: 1
vat_loss_weight:
  desc: null
  value: 1.0
wcp_loss:
  desc: null
  value: 0
wcp_loss_weight:
  desc: null
  value: 1.0
