wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
backbone:
  desc: null
  value: densenet121
base_lr:
  desc: null
  value: 0.0001
baseline:
  desc: null
  value: 0
batch_size:
  desc: null
  value: 32
bnm_loss:
  desc: null
  value: 0
bnm_loss_improve:
  desc: null
  value: 0
bnm_loss_weight:
  desc: null
  value: 1.0
class_names:
  desc: null
  value:
  - Melanoma
  - Melanocytic nevus
  - Basal cell carcinoma
  - Actinic keratosis
  - Benign keratosis
  - Dermatofibroma
  - Vascular lesion
class_num:
  desc: null
  value:
  - 1113.0
  - 6705.0
  - 514.0
  - 327.0
  - 1099.0
  - 115.0
  - 142.0
consistency:
  desc: null
  value: 1
consistency_began_epoch:
  desc: null
  value: 20
consistency_rampup:
  desc: null
  value: 30
consistency_relation_weight:
  desc: null
  value: 1.0
consistency_type:
  desc: null
  value: mse
csv_file_test:
  desc: null
  value: ../dataset/skin/testing.csv
csv_file_train:
  desc: null
  value: ../dataset/skin/training.csv
csv_file_val:
  desc: null
  value: ../dataset/skin/validation.csv
deterministic:
  desc: null
  value: 1
drop_rate:
  desc: null
  value: 0.2
ema_consistency:
  desc: null
  value: 1
ema_decay:
  desc: null
  value: 0.99
entropy_loss:
  desc: null
  value: 0
entropy_loss_weight:
  desc: null
  value: 1.0
epochs:
  desc: null
  value: 100
exp:
  desc: null
  value: 0709_wcp_test
global_step:
  desc: null
  value: 0
gpu:
  desc: null
  value: 0,1
label_uncertainty:
  desc: null
  value: U-Ones
labeled_bs:
  desc: null
  value: 8
labeled_rate:
  desc: null
  value: 0.2
multi_scale_densenet:
  desc: null
  value: 0
resize:
  desc: null
  value: 224
resume:
  desc: null
  value: null
root_path:
  desc: null
  value: ../dataset/skin/training_data/
scale1_weight:
  desc: null
  value: 1.0
scale2_weight:
  desc: null
  value: 1.0
scale3_weight:
  desc: null
  value: 1.0
scale4_weight:
  desc: null
  value: 1.0
seed:
  desc: null
  value: 22000
start_epoch:
  desc: null
  value: 0
supCon_loss:
  desc: null
  value: 0
supCon_loss_weight:
  desc: null
  value: 1.0
supervise_level:
  desc: null
  value: semi
task:
  desc: null
  value: skin
vat_dis_type:
  desc: null
  value: mae
vat_loss:
  desc: null
  value: 1
vat_loss_weight:
  desc: null
  value: 1.0
wcp_loss:
  desc: null
  value: 0
wcp_loss_weight:
  desc: null
  value: 1.0
